# Numpy Arrays

In [2]:
import numpy as np

In [5]:
arr: np.ndarray = np.array([1, 2, 3])

In [6]:
arr

array([1, 2, 3])

In [7]:
type(arr)

numpy.ndarray

In [9]:
np.ndarray

numpy.ndarray

In [10]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.linspace(0, 9, 10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])