# Numpy

Playing around with Numpy

In [17]:
import numpy as np

## Numpy Arrays

In [8]:
# Making an array

arr: np.ndarray = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [9]:
# The datatype for the numpy array is numpy's own ndarray

type(arr)

numpy.ndarray

In [44]:
# For the datatype of the elements of the array, we can do this

arr.dtype

dtype('int64')

In [10]:
# A quick way to make a numpy array based off a range

np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
# Numpy array of zeros and ones

zeros: np.ndarray = np.zeros(5)
ones: np.ndarray = np.ones(5)

print(zeros, ones)

[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.]


In [17]:
# The linspace function return evenly spaced numbers over a specified interval.
# In this case it return the numbers from 0 to 9 with 10 evenly spaced intervals.

np.linspace(0, 9, 10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [6]:
# Identity Matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Numpy Random

In [6]:
# A regular random array with a uniform distribution

np.random.rand(5)
np.random.rand(2, 2)

array([[0.15623977, 0.58041577],
       [0.74522447, 0.855533  ]])

In [9]:
# Normal Distribution center around 0

np.random.randn(5)

array([ 0.71976975,  0.47104807,  0.59792207, -1.33284353,  0.45667921])

In [16]:
# Returns random integer(s)

np.random.randint(0, 100, 100)

array([95,  8, 91, 48, 81, 99, 40,  3, 47, 43, 37, 82,  5, 29, 68, 89, 18,
       13,  7, 85, 16, 84, 97, 11, 78,  4,  8, 95, 80, 90, 13, 42, 26, 37,
       60, 94, 17, 65, 12, 70, 45, 64, 79, 56, 11, 56, 78, 23,  8, 99, 83,
       52, 55, 84, 52, 34, 60, 51, 18, 31,  2, 92,  6,  3,  9, 48, 33, 55,
       50, 22, 49, 58, 36, 48, 72, 22,  4, 22, 74, 62,  0, 57, 84, 67, 82,
       56, 93, 32, 60, 86, 17, 88, 80, 22,  3, 96, 35, 96, 14, 38])

## Numpy Array Manipulation

In [19]:
arr = np.random.randint(0, 100, 10)

In [20]:
arr

array([37,  8,  5, 82, 87,  7, 93, 66, 78, 53])

### Shape of array

Numpy can also handle multi dimensional array. We can get the shape
via `.shape` and change it shape via `.reshape(m, n, ...)`

In [52]:
# Reshaping array, note that the product of the shape must match
# the number of elements

# Notice that arr didn't get modified inplace

print(arr.shape)

arr2d = arr.reshape(2, 5)

print(arr2d.shape)
arr

(10,)
(2, 5)


array([37,  8,  5, 82, 87,  7, 93, 66, 78, 53])

### Getting  max and min values from array

Numpy has `.max()` and `.min()` functions. It's self explanatory.
`.argmax()` and `.argmin()` will return the index of said max and min value.

When given to a multi dimentional array, it'll return the answer as if it's a one-d array.

In [27]:
# Getting max value

arr.max()

93

In [28]:
# Getting min value

arr.min()

5

In [29]:
arr.argmax()

6

In [30]:
arr.argmin()

2

In [35]:
arr2d.argmax()
arr2d

array([[37,  8,  5, 82, 87],
       [ 7, 93, 66, 78, 53]])

In [36]:
arr2d.argmin()

2