# Numpy

Playing around with Numpy

In [17]:
import numpy as np

## Numpy Arrays

In [8]:
# Making an array

arr: np.ndarray = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [9]:
# The datatype for the numpy array is numpy's own ndarray

type(arr)

numpy.ndarray

In [44]:
# For the datatype of the elements of the array, we can do this

arr.dtype

dtype('int64')

In [10]:
# A quick way to make a numpy array based off a range

np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
# Numpy array of zeros and ones

zeros: np.ndarray = np.zeros(5)
ones: np.ndarray = np.ones(5)

print(zeros, ones)

[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.]


In [17]:
# The linspace function return evenly spaced numbers over a specified interval.
# In this case it return the numbers from 0 to 9 with 10 evenly spaced intervals.

np.linspace(0, 9, 10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [6]:
# Identity Matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Numpy Random

In [6]:
# A regular random array with a uniform distribution

np.random.rand(5)
np.random.rand(2, 2)

array([[0.15623977, 0.58041577],
       [0.74522447, 0.855533  ]])

In [9]:
# Normal Distribution center around 0

np.random.randn(5)

array([ 0.71976975,  0.47104807,  0.59792207, -1.33284353,  0.45667921])

In [16]:
# Returns random integer(s)

np.random.randint(0, 100, 100)

array([95,  8, 91, 48, 81, 99, 40,  3, 47, 43, 37, 82,  5, 29, 68, 89, 18,
       13,  7, 85, 16, 84, 97, 11, 78,  4,  8, 95, 80, 90, 13, 42, 26, 37,
       60, 94, 17, 65, 12, 70, 45, 64, 79, 56, 11, 56, 78, 23,  8, 99, 83,
       52, 55, 84, 52, 34, 60, 51, 18, 31,  2, 92,  6,  3,  9, 48, 33, 55,
       50, 22, 49, 58, 36, 48, 72, 22,  4, 22, 74, 62,  0, 57, 84, 67, 82,
       56, 93, 32, 60, 86, 17, 88, 80, 22,  3, 96, 35, 96, 14, 38])

## Numpy Array Manipulation

In [19]:
arr = np.random.randint(0, 100, 10)

In [20]:
arr

array([37,  8,  5, 82, 87,  7, 93, 66, 78, 53])

### Shape of array

Numpy can also handle multi dimensional array. We can get the shape
via `.shape` and change it shape via `.reshape(m, n, ...)`

In [52]:
# Reshaping array, note that the product of the shape must match
# the number of elements

# Notice that arr didn't get modified inplace

print(arr.shape)

arr2d = arr.reshape(2, 5)

print(arr2d.shape)
arr

(10,)
(2, 5)


array([37,  8,  5, 82, 87,  7, 93, 66, 78, 53])

### Getting  max and min values from array

Numpy has `.max()` and `.min()` functions. It's self explanatory.
`.argmax()` and `.argmin()` will return the index of said max and min value.

When given to a multi dimentional array, it'll return the answer as if it's a one-d array.

In [27]:
# Getting max value

arr.max()

93

In [28]:
# Getting min value

arr.min()

5

In [29]:
arr.argmax()

6

In [30]:
arr.argmin()

2

In [35]:
arr2d.argmax()
arr2d

array([[37,  8,  5, 82, 87],
       [ 7, 93, 66, 78, 53]])

In [36]:
arr2d.argmin()

2

## Numpy Array Indexing

Just like regular python arrays, we can index numpy arrays.
The syntax is similar to python array indexing with the square bracket notation.

In [55]:
arr: np.ndarray = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr[5]

5

In [56]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [58]:
arr[5:8]

array([5, 6, 7])

## Manipulating slices

Slicing an array returns a reference to the sliced array.

In [74]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
# Here, I'm getting a sliced of the array

sliced_of_arr = arr[:6]
sliced_of_arr

array([0, 1, 2, 3, 4, 5])

In [65]:
# Changing the content of the sliced array will result in changing
# the elements of the original array to in the position we just sliced from

sliced_of_arr[:] = 99

arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [67]:
# If we want a copy, use `.copy()`

arr_copy = arr.copy()

In [73]:
arr_copy[0] = 20
print(arr_copy, arr)


[20 99 99 99 99 99  6  7  8  9 10] [99 99 99 99 99 99  6  7  8  9 10]


In [86]:
# With 2d arrays you can index via double square bracket or just single square brakcet with a comma

arr2d = np.linspace(0, 24, 25)
arr2d = arr2d.reshape(5, 5)

arr2d

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [88]:
arr2d[1, 2] == arr2d[1][2]

True

In [89]:
arr2d[:2, 1:]

array([[1., 2., 3., 4.],
       [6., 7., 8., 9.]])

## Conditional Selections

In [91]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [97]:
arr[arr < 3]

array([1, 2])

In [102]:
# Doing conditional indexing will return a one-d array

arr_2d = np.arange(50).reshape(5, 10)
arr_2d[arr_2d < 30]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## Numpy Operations

- Array with Array
- Array with Scalars
- Universal Array Functions

You can check all of numpy's universal functions [here](https://numpy.org/doc/stable/reference/ufuncs.html)

In [107]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [105]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [106]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [108]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [109]:
arr / arr

<ipython-input-109-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [112]:
n = (arr / arr)[0]
type(n)

<ipython-input-112-8c4712fdf566>:1: RuntimeWarning: invalid value encountered in true_divide
  n = (arr / arr)[0]


numpy.float64

In [113]:
1 / arr

<ipython-input-113-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [114]:
np.inf

inf

In [116]:
# Square Root

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [118]:
# exponential

np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [119]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [120]:
np.log(arr)

<ipython-input-120-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [122]:
np.sin(np.pi/2)

1.0