# Numpy Exercises

Check [here](https://www.w3resource.com/python-exercises/numpy/basic/index.php) for source 

In [1]:
import numpy as np

1.Write a NumPy program to get the numpy version and show numpy build configuration.

In [3]:
print(np.__version__)
print(np.show_config())

1.20.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


2. Write a NumPy program to  get help on the add function.

In [6]:
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [8]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

3. Write a NumPy program to test whether none of the elements of a given array is zero.

In [13]:
# np.all looks at the truthyness of all elements inside the array

arr = np.arange(1, 10)
np.all(arr)

True

4. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [19]:
arr2 = np.array([0,0,0,0,1])

np.any(arr2)

True

5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [38]:
arr3 = np.array([np.inf, 1, 2, np.nan, -np.inf, 1 + 1j])
print(np.isfinite(arr3))
print(np.isinf(arr3))


[False  True  True False False  True]
[ True False False False  True False]


6. Write a NumPy program to test element-wise for positive or negative infinity.

In [33]:
np.isinf(arr3)

array([ True, False, False, False,  True])

7. Write a NumPy program to test element-wise for NaN of a given array.

In [34]:
np.isnan(arr3)

array([False, False, False,  True, False])

8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not. 

In [39]:
np.iscomplex(arr3)

array([False, False, False, False, False,  True])

In [42]:
np.isreal(arr3)

array([ True,  True,  True,  True,  True, False])

In [44]:
np.isscalar(3.1)

True

9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance. 

In [52]:
arr4 = arr3.copy()
print(arr3)
print(arr4)
np.allclose(arr3, arr4, equal_nan=True)

[ inf+0.j   1.+0.j   2.+0.j  nan+0.j -inf+0.j   1.+1.j]
[ inf+0.j   1.+0.j   2.+0.j  nan+0.j -inf+0.j   1.+1.j]


True

In [54]:
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))


False


In [55]:
np.info(np.allclose)

 allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)

Returns True if two arrays are element-wise equal within a tolerance.

The tolerance values are positive, typically very small numbers.  The
relative difference (`rtol` * abs(`b`)) and the absolute difference
`atol` are added together to compare against the absolute difference
between `a` and `b`.

NaNs are treated as equal if they are in the same place and if
``equal_nan=True``.  Infs are treated as equal if they are in the same
place and of the same sign in both arrays.

Parameters
----------
a, b : array_like
    Input arrays to compare.
rtol : float
    The relative tolerance parameter (see Notes).
atol : float
    The absolute tolerance parameter (see Notes).
equal_nan : bool
    Whether to compare NaN's as equal.  If True, NaN's in `a` will be
    considered equal to NaN's in `b` in the output array.

    .. versionadded:: 1.10.0

Returns
-------
allclose : bool
    Returns True if the two arrays are equal within the given

10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [57]:
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]
